name: PNPM CI

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/pnpm-ci.yml"
            - "taceo-merces1-client-js/**"
            - "taceo-merces1-x402-js/**"
            - "taceo-merces1-x402-react-app/**"
    pull_request:
        paths:
            - ".github/workflows/pnpm-ci.yml"
            - "taceo-merces1-client-js/**"
            - "taceo-merces1-x402-js/**"
            - "taceo-merces1-x402-react-app/**"

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    ci:
        name: Test & Lint (${{ matrix.package }})
        runs-on: [ubuntu-latest]
        timeout-minutes: 15
        strategy:
            fail-fast: false
            matrix:
                package:
                    - taceo-merces1-client-js
                    - taceo-merces1-x402-js
                    - taceo-merces1-x402-react-app
        defaults:
            run:
                working-directory: ${{ matrix.package }}
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
              with:
                  package_json_file: ${{ matrix.package }}/package.json

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version-file: ${{ matrix.package }}/.nvmrc
                  cache: "pnpm"
                  cache-dependency-path: ${{ matrix.package }}/pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              if: matrix.package != 'taceo-merces1-x402-react-app'
              run: pnpm build

            - name: Lint
              run: pnpm lint

            - name: Typecheck
              run: pnpm typecheck

            - name: Check formatting
              run: pnpm exec prettier --check .

            # not tests exist yet, full e2e tests needs setup running
            # - name: Test
            #   run: pnpm test
